-- Migración para recrear la tabla auditoria
-- Ejecutar este SQL directamente en la base de datos PostgreSQL

-- Crear la tabla auditoria
CREATE TABLE IF NOT EXISTS auditoria (
  id_aud INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  id_usuario VARCHAR(150),
  fecha TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
  accion VARCHAR(100),
  tabla_afectada VARCHAR(100),
  dato_anterior JSONB,
  dato_despues JSONB,
  user_agent VARCHAR(255),
  endpoint VARCHAR(255),
  estado VARCHAR(50),
  descripcion VARCHAR(255),
  tiempo_procesamiento INTEGER,
  CONSTRAINT auditoria_id_usuario_fkey 
    FOREIGN KEY (id_usuario) 
    REFERENCES usuarios(id_usuario) 
    ON DELETE NO ACTION 
    ON UPDATE NO ACTION
);

-- Crear índices
CREATE INDEX IF NOT EXISTS idx_auditoria_fecha ON auditoria(fecha);
CREATE INDEX IF NOT EXISTS idx_auditoria_usuario ON auditoria(id_usuario);

-- Verificar que la tabla se creó correctamente
-- SELECT table_name, column_name, data_type, character_maximum_length
-- FROM information_schema.columns
-- WHERE table_name = 'auditoria'
-- ORDER BY ordinal_position;








